name: CI

on:
    pull_request:
    push:

jobs:
    shepherd:
        name: Psalm Shepherd
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Psalm
              uses: docker://vimeo/psalm-github-actions
              with:
                  args: --shepherd
